
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label lb1;
	private global::Gtk.Label lb2;
	private global::Gtk.Label lb3;
	private global::Gtk.Entry entry2;
	private global::Gtk.Entry entry3;
	private global::Gtk.Entry entry1;
	private global::Gtk.Button bu1;
	private global::Gtk.Button bu2;
	private global::Gtk.Button bu3;
	private global::Gtk.Button bu4;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lb1 = new global::Gtk.Label ();
		this.lb1.Name = "lb1";
		this.lb1.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero 1");
		this.fixed1.Add (this.lb1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lb1]));
		w1.X = 20;
		w1.Y = 19;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lb2 = new global::Gtk.Label ();
		this.lb2.Name = "lb2";
		this.lb2.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero 2");
		this.fixed1.Add (this.lb2);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lb2]));
		w2.X = 18;
		w2.Y = 61;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lb3 = new global::Gtk.Label ();
		this.lb3.Name = "lb3";
		this.lb3.LabelProp = global::Mono.Unix.Catalog.GetString ("Resultado");
		this.fixed1.Add (this.lb3);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.lb3]));
		w3.X = 17;
		w3.Y = 110;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry2 = new global::Gtk.Entry ();
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '●';
		this.fixed1.Add (this.entry2);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry2]));
		w4.X = 109;
		w4.Y = 53;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry3 = new global::Gtk.Entry ();
		this.entry3.CanFocus = true;
		this.entry3.Name = "entry3";
		this.entry3.IsEditable = true;
		this.entry3.InvisibleChar = '●';
		this.fixed1.Add (this.entry3);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry3]));
		w5.X = 111;
		w5.Y = 99;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entry1 = new global::Gtk.Entry ();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '●';
		this.fixed1.Add (this.entry1);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entry1]));
		w6.X = 109;
		w6.Y = 8;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.bu1 = new global::Gtk.Button ();
		this.bu1.CanFocus = true;
		this.bu1.Name = "bu1";
		this.bu1.UseUnderline = true;
		this.bu1.Label = global::Mono.Unix.Catalog.GetString ("Sumar");
		this.fixed1.Add (this.bu1);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.bu1]));
		w7.X = 24;
		w7.Y = 235;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.bu2 = new global::Gtk.Button ();
		this.bu2.CanFocus = true;
		this.bu2.Name = "bu2";
		this.bu2.UseUnderline = true;
		this.bu2.Label = global::Mono.Unix.Catalog.GetString ("Restar");
		this.fixed1.Add (this.bu2);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.bu2]));
		w8.X = 111;
		w8.Y = 234;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.bu3 = new global::Gtk.Button ();
		this.bu3.CanFocus = true;
		this.bu3.Name = "bu3";
		this.bu3.UseUnderline = true;
		this.bu3.Label = global::Mono.Unix.Catalog.GetString ("Multiplicar");
		this.fixed1.Add (this.bu3);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.bu3]));
		w9.X = 195;
		w9.Y = 233;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.bu4 = new global::Gtk.Button ();
		this.bu4.CanFocus = true;
		this.bu4.Name = "bu4";
		this.bu4.UseUnderline = true;
		this.bu4.Label = global::Mono.Unix.Catalog.GetString ("Dividir");
		this.fixed1.Add (this.bu4);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.bu4]));
		w10.X = 304;
		w10.Y = 233;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 437;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.bu1.Clicked += new global::System.EventHandler (this.OnBu1Clicked);
		this.bu2.Clicked += new global::System.EventHandler (this.OnBu2Clicked);
		this.bu3.Clicked += new global::System.EventHandler (this.OnBu3Clicked);
		this.bu4.Clicked += new global::System.EventHandler (this.OnBu4Clicked);
	}
}
